services:
  # 1. Serviço da nossa API Node.js
  - type: web
    name: auth-api-app
    env: docker
    repo: https://github.com/dcfdl/api_authentication_docker.git
    region: oregon
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: MONGO_URI
        fromService:
          type: pserv
          name: auth-api-mongo
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: pserv
          name: auth-api-redis
          property: connectionString
      - key: JWT_SECRET
        sync: false # Indica que é um segredo e será inserido manualmente
      - key: JWT_REFRESH_SECRET
        sync: false # Indica que é um segredo e será inserido manualmente
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d

  # 2. Serviço do Banco de Dados MongoDB
  - type: pserv
    name: auth-api-mongo
    env: docker
    repo: https://github.com/dcfdl/api_authentication_docker.git 
    image:
      dockerfilePath: mongo.Dockerfile
    region: oregon
    plan: free
    disk:
      name: mongodb-data
      mountPath: /data/db
      sizeGB: 1
    envVars:
      - key: MONGO_INITDB_ROOT_USERNAME
        sync: false
      - key: MONGO_INITDB_ROOT_PASSWORD
        sync: false

  # 3. Serviço do Cache Redis
  - type: pserv
    name: auth-api-redis
    env: redis
    region: oregon
    plan: free